// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by internal/generate/tags/main.go; DO NOT EDIT.
package logs

import (
	"context"

	"github.com/YakDriver/smarterr"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	awstypes "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/errs"
	"github.com/hashicorp/terraform-provider-aws/internal/logging"
	tftags "github.com/hashicorp/terraform-provider-aws/internal/tags"
	"github.com/hashicorp/terraform-provider-aws/internal/types/option"
	"github.com/hashicorp/terraform-provider-aws/names"
)

// listTags lists logs service tags.
// The identifier is typically the Amazon Resource Name (ARN), although
// it may also be a different identifier depending on the service.
func listTags(ctx context.Context, conn *cloudwatchlogs.Client, identifier string, optFns ...func(*cloudwatchlogs.Options)) (tftags.KeyValueTags, error) {
	// Rate limit: CloudWatch Logs ListTagsForResource has 15 TPS limit
	if err := waitForListTagsRateLimit(ctx); err != nil {
		return tftags.New(ctx, nil), smarterr.NewError(err)
	}

	tflog.Debug(ctx, "Fetching tags for log group", map[string]any{
		"resource_arn": identifier,
	})

	input := cloudwatchlogs.ListTagsForResourceInput{
		ResourceArn: aws.String(identifier),
	}

	// Retry up to 3 times if throttled (SDK retries are disabled for throttling)
	var output *cloudwatchlogs.ListTagsForResourceOutput
	var err error
	maxRetries := 3
	
	for attempt := 1; attempt <= maxRetries; attempt++ {
		output, err = conn.ListTagsForResource(ctx, &input, optFns...)
		
		if err == nil {
			break // Success
		}
		
		// Check if it's a throttling error
		if errs.IsAErrorMessageContains[*awstypes.ThrottlingException](err, "Rate exceeded") {
			if attempt < maxRetries {
				// Wait and retry (our rate limiter will enforce proper delay)
				tflog.Debug(ctx, "Throttled - retrying after rate limit delay", map[string]any{
					"attempt":      attempt,
					"max_retries":  maxRetries,
					"resource_arn": identifier,
				})
				
				// Wait for rate limiter before retry
				if waitErr := waitForListTagsRateLimit(ctx); waitErr != nil {
					return tftags.New(ctx, nil), smarterr.NewError(waitErr)
				}
				continue
			}
			// Max retries exceeded
			tflog.Warn(ctx, "Max retries exceeded for throttling", map[string]any{
				"resource_arn": identifier,
			})
		}
		
		// Non-throttling error or max retries exceeded
		break
	}

	if err != nil {
		return tftags.New(ctx, nil), smarterr.NewError(err)
	}

	return keyValueTags(ctx, output.Tags), nil
}

// ListTags lists logs service tags and set them in Context.
// It is called from outside this package.
func (p *servicePackage) ListTags(ctx context.Context, meta any, identifier string) error {
	tags, err := listTags(ctx, meta.(*conns.AWSClient).LogsClient(ctx), identifier)

	if err != nil {
		return smarterr.NewError(err)
	}

	if inContext, ok := tftags.FromContext(ctx); ok {
		inContext.TagsOut = option.Some(tags)
	}

	return nil
}

// map[string]string handling

// svcTags returns logs service tags.
func svcTags(tags tftags.KeyValueTags) map[string]string {
	return tags.Map()
}

// keyValueTags creates tftags.KeyValueTags from logs service tags.
func keyValueTags(ctx context.Context, tags map[string]string) tftags.KeyValueTags {
	return tftags.New(ctx, tags)
}

// getTagsIn returns logs service tags from Context.
// nil is returned if there are no input tags.
func getTagsIn(ctx context.Context) map[string]string {
	if inContext, ok := tftags.FromContext(ctx); ok {
		if tags := svcTags(inContext.TagsIn.UnwrapOrDefault()); len(tags) > 0 {
			return tags
		}
	}

	return nil
}

// setTagsOut sets logs service tags in Context.
func setTagsOut(ctx context.Context, tags map[string]string) {
	if inContext, ok := tftags.FromContext(ctx); ok {
		inContext.TagsOut = option.Some(keyValueTags(ctx, tags))
	}
}

// createTags creates logs service tags for new resources.
func createTags(ctx context.Context, conn *cloudwatchlogs.Client, identifier string, tags map[string]string, optFns ...func(*cloudwatchlogs.Options)) error {
	if len(tags) == 0 {
		return nil
	}

	return updateTags(ctx, conn, identifier, nil, tags, optFns...)
}

// updateTags updates logs service tags.
// The identifier is typically the Amazon Resource Name (ARN), although
// it may also be a different identifier depending on the service.
func updateTags(ctx context.Context, conn *cloudwatchlogs.Client, identifier string, oldTagsMap, newTagsMap any, optFns ...func(*cloudwatchlogs.Options)) error {
	oldTags := tftags.New(ctx, oldTagsMap)
	newTags := tftags.New(ctx, newTagsMap)

	ctx = tflog.SetField(ctx, logging.KeyResourceId, identifier)

	removedTags := oldTags.Removed(newTags)
	removedTags = removedTags.IgnoreSystem(names.Logs)
	if len(removedTags) > 0 {
		input := cloudwatchlogs.UntagResourceInput{
			ResourceArn: aws.String(identifier),
			TagKeys:     removedTags.Keys(),
		}

		_, err := conn.UntagResource(ctx, &input, optFns...)

		if err != nil {
			return smarterr.NewError(err)
		}
	}

	updatedTags := oldTags.Updated(newTags)
	updatedTags = updatedTags.IgnoreSystem(names.Logs)
	if len(updatedTags) > 0 {
		input := cloudwatchlogs.TagResourceInput{
			ResourceArn: aws.String(identifier),
			Tags:        svcTags(updatedTags),
		}

		_, err := conn.TagResource(ctx, &input, optFns...)

		if err != nil {
			return smarterr.NewError(err)
		}
	}

	return nil
}

// UpdateTags updates logs service tags.
// It is called from outside this package.
func (p *servicePackage) UpdateTags(ctx context.Context, meta any, identifier string, oldTags, newTags any) error {
	return updateTags(ctx, meta.(*conns.AWSClient).LogsClient(ctx), identifier, oldTags, newTags)
}
